# Creating a Java Archive File on Push
name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'Oracle'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: target/*.jar