# This file Generates the Javadoc of our
# Project on Push to the main branch

name: Generate Javadoc

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate Javadoc
        run: |
          mvn javadoc:javadoc \
          -Dmaven.compiler.source=21 \
          -Dmaven.compiler.target=21 \
          -Dmaven.compiler.release=21 \
          -Dmaven.javadoc.failOnError=false \
          -DadditionalJOption=-J--enable-preview

      - name: Upload Javadoc
        uses: actions/upload-artifact@v3
        with:
          name: JavadocArtifact
          path: target/site/apidocs/