# Java CI with Maven and Test Execution
# on push and pull-request for now
# will maybe delete on push later -Michi
# (Assignment relevant)
name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: TestArtifact
          path: target/*.jar
